build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "MS Dhoni - Developer"
    email: "mahi@gmail.com"
  onCallSupport:
    - (777) 777-8567
    - (777) 777-7565
